######### REGISTER
POST https://todo-qa-with-ts-backend.onrender.com/api/auth/register
Content-Type: application/json

{
  "name":"A V V Satyanarayana",
  "email":"satya@yopmail.com",
  "password":"Srinivas@8",
  "phone":"919177629841",
  "profilePicture":"https://res.cloudinary.com/dakda5ni3/image/upload/v1720865877/gkfphz7dd4kru4eiwmbx.jpg",
  "bio":"Bank Employee",
  "isAdmin":false
}

######### LOGIN
POST https://todo-qa-with-ts-backend.onrender.com/api/auth/login
Content-Type: application/json

{
  "emailOrPhone":"srinivas@yopmail.com",
  "password":"Srinivas@8"
}

######## GET ALL USERS
GET https://todo-qa-with-ts-backend.onrender.com/api/auth
Content-Type: application/json

######### GET USER WITH ID
GET https://todo-qa-with-ts-backend.onrender.com/api/auth/66a3d2d6063086539ee99def
Content-Type: application/json

####### UPDATE USER WITH ID
PATCH https://todo-qa-with-ts-backend.onrender.com/api/auth/66a3c72fada193bfc674642b
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjhlYThmNWYyOTFjZTk0ODNiNjVmODMiLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE3MjA2MjU0ODN9.4-ewiskwhpzKvHBaZprmqMbQti-8t9nTyBKvvnAfzaY

{
  "name":"Srinivas Akella",
  "email":"srinivas.akella@yopmail.com",
  "phone":"917995643201",
  "profilePicture":"https://res.cloudinary.com/dakda5ni3/image/upload/v1717485958/jyqgeifwqktlyzkgvr7n.png",
  "bio":"A MERN & FULL stack developer with 2+ years of experience...",
  "isAdmin":false
}

######## UPDATE PASSWORD
PATCH https://todo-qa-with-ts-backend.onrender.com/api/auth/668ea8f5f291ce9483b65f83/updatePassword
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjhlYThmNWYyOTFjZTk0ODNiNjVmODMiLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE3MjA2MjU0ODN9.4-ewiskwhpzKvHBaZprmqMbQti-8t9nTyBKvvnAfzaY

{
  "oldPassword":"Srinivas@8",
  "newPassword":"SrinivasAkella@14"
}

########### DELETE USER
DELETE https://todo-qa-with-ts-backend.onrender.com/api/auth/6692549ff78a68885d33ef03/delete
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjhlYThmNWYyOTFjZTk0ODNiNjVmODMiLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE3MjA3ODA4ODN9.zGMNWU1QJGC9xfJf4oYpSp60bZBSqvPiZ8WqkTPI4Ro

############# CREATE QA
POST https://todo-qa-with-ts-backend.onrender.com/api/qa/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjhlYThmNWYyOTFjZTk0ODNiNjVmODMiLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE3MjA2MjU0ODN9.4-ewiskwhpzKvHBaZprmqMbQti-8t9nTyBKvvnAfzaY

{
  "question":"What is ReactJS ?",
  "answer":"ReactJS is a javascript library that is used to build user interfaces with advanced logics and animations with management of state, props and api integration.",
  "toolId":"3",
  "userId":"66a3d2d6063086539ee99def"
}

############ GET QA BY TOOL ID
GET https://todo-qa-with-ts-backend.onrender.com/api/qa/668ea8f5f291ce9483b65f83/3
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjhlYThmNWYyOTFjZTk0ODNiNjVmODMiLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE3MjA2MjU0ODN9.4-ewiskwhpzKvHBaZprmqMbQti-8t9nTyBKvvnAfzaY

############## UPDATE QA 
PATCH https://todo-qa-with-ts-backend.onrender.com/api/qa/66916b8c04b5fc4216f00068/668ea8f5f291ce9483b65f83
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjhlYThmNWYyOTFjZTk0ODNiNjVmODMiLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE3MjA2MjU0ODN9.4-ewiskwhpzKvHBaZprmqMbQti-8t9nTyBKvvnAfzaY

{
  "question":"What is React ?",
  "answer":"React is a JavaScript library that is used to build/develop user interfaces.",
  "toolId":"3"
}

############# DELETE QA
DELETE https://todo-qa-with-ts-backend.onrender.com/api/qa/668eae7d6d917c9032e4832a/668ea8f5f291ce9483b65f83
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjhlYThmNWYyOTFjZTk0ODNiNjVmODMiLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE3MjA2MjU0ODN9.4-ewiskwhpzKvHBaZprmqMbQti-8t9nTyBKvvnAfzaY

############# CREATE TODO
POST https://todo-qa-with-ts-backend.onrender.com/api/todo/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjkxMDZiZGQ2MGQ0Y2RiZTRjYTdhNDIiLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE3MjA3ODA5ODh9.W0d90MBCpCeGhsx7zbHy6fRC97kfGof8NLSICLzcTRs

{
  "title":"Learn NodeJS",
  "description":"A Sample description",
  "deadline":"2024-07-25",
  "userId":"669106bdd60d4cdbe4ca7a42",
  "urgency":false
}

############# GET TODO WITH USERID
GET https://todo-qa-with-ts-backend.onrender.com/api/todo/669106bdd60d4cdbe4ca7a42
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjkxMDZiZGQ2MGQ0Y2RiZTRjYTdhNDIiLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE3MjA3ODA5ODh9.W0d90MBCpCeGhsx7zbHy6fRC97kfGof8NLSICLzcTRs


############### UPDATE TODO
PATCH https://todo-qa-with-ts-backend.onrender.com/api/todo/66910a4b287a7f85ea4c5fd0
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjkxMDZiZGQ2MGQ0Y2RiZTRjYTdhNDIiLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE3MjA3OTk3NDR9.-63Qg1mjJOkrqw-RsxyFGDMxjHSjx0b2oQwU55ghyhE

{
  "title":"Learn JavaScript",
  "description":"A Sample description on learning React with Typescript",
  "deadline":"2024-07-25",
  "userId":"669106bdd60d4cdbe4ca7a42",
  "urgency":true
}

########## DELETE TODO
DELETE https://todo-qa-with-ts-backend.onrender.com/api/todo/66910a4b287a7f85ea4c5fd0/669106bdd60d4cdbe4ca7a42
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjkxMDZiZGQ2MGQ0Y2RiZTRjYTdhNDIiLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE3MjA3OTk3NDR9.-63Qg1mjJOkrqw-RsxyFGDMxjHSjx0b2oQwU55ghyhE

############ CREATED USER BY ADMIN
POST https://todo-qa-with-ts-backend.onrender.com/api/admin/createUser/669250d6c617e4760f3d31f1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjkyNTBkNmM2MTdlNDc2MGYzZDMxZjEiLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE3MjA4NjUwMDZ9.KWJcGYUMm4W7SEWyr-_5fqQzmode3_dcSsYDqXBC3A4

{
  "name":"A V V Satyanarayana",
  "email":"satya@yopmail.com",
  "password":"Srinivas@8",
  "phone":"919177629841",
  "profilePicture":"https://res.cloudinary.com/dakda5ni3/image/upload/v1720865268/jnwxv8frftasqbdvvue6.jpg",
  "bio":"Bank Employee"
}

############ GET ALL USERS BY ADMIN
GET https://todo-qa-with-ts-backend.onrender.com/api/admin/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjkyNTBkNmM2MTdlNDc2MGYzZDMxZjEiLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE3MjA4NjUwMDZ9.KWJcGYUMm4W7SEWyr-_5fqQzmode3_dcSsYDqXBC3A4

################# UPDATE USER BY ADMIN
PATCH https://todo-qa-with-ts-backend.onrender.com/api/admin/updateUser/66a3cc0aada193bfc6746445
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjkyNTBkNmM2MTdlNDc2MGYzZDMxZjEiLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE3MjA4NjUwMDZ9.KWJcGYUMm4W7SEWyr-_5fqQzmode3_dcSsYDqXBC3A4

{
  "name":"A.V.V.Satyanarayana",
  "email":"satya@yopmail.com",
  "password":"Srinivas@8",
  "phone":"919177629841",
  "profilePicture":"https://res.cloudinary.com/dakda5ni3/image/upload/v1720865268/jnwxv8frftasqbdvvue6.jpg",
  "bio":"Bank Employee"
}

########### DELETE A USER BY ADMIN
DELETE https://todo-qa-with-ts-backend.onrender.com/api/admin/deleteUser/66a3cc0aada193bfc6746445/669250d6c617e4760f3d31f1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjkyNTBkNmM2MTdlNDc2MGYzZDMxZjEiLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE3MjA4NjUwMDZ9.KWJcGYUMm4W7SEWyr-_5fqQzmode3_dcSsYDqXBC3A4


########### CREATE QA BY ADMIN
POST https://todo-qa-with-ts-backend.onrender.com/api/admin/createQA/66a3d2d6063086539ee99def/669250d6c617e4760f3d31f1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjkyNTBkNmM2MTdlNDc2MGYzZDMxZjEiLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE3MjIwMTMxNTF9.HhnFw98y1wT1zDoEpYHHUUUN2Q_olbltjZTcJtnkDYE


{
  "question":"What is JavaScript ?",
  "answer":"JavaScript is a web technology that can be used to build interactive web pages and web applications. It is an interpreted programming language that conforms to the ECMAScript specification.",
  "toolId":"3",
  "importance":"Important"
}

############# GET A USER'S QA
GET https://todo-qa-with-ts-backend.onrender.com/api/admin/qa/66a3d2d6063086539ee99def
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjkyNTBkNmM2MTdlNDc2MGYzZDMxZjEiLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE3MjIwMTMxNTF9.HhnFw98y1wT1zDoEpYHHUUUN2Q_olbltjZTcJtnkDYE

########### UPDATE QA OF A USER BY ADMIN
PATCH https://todo-qa-with-ts-backend.onrender.com/api/admin/updateQa/66a3d2d6063086539ee99def/66a3ddbbb4bcf37ad42f6c1b/669250d6c617e4760f3d31f1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjkyNTBkNmM2MTdlNDc2MGYzZDMxZjEiLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE3MjIwMTMxNTF9.HhnFw98y1wT1zDoEpYHHUUUN2Q_olbltjZTcJtnkDYE

{
  "question":"What is NodeJs ?",
  "answer":"NodeJs is a JS Framework that is used to build server side apps accepting concurrent requests with async functions and promises",
  "toolId":"2",
  "importance":"Important"
}


############ DELETE A QA OF A USER BY ADMIN
DELETE https://todo-qa-with-ts-backend.onrender.com/api/admin/deleteQA/66a3d2d6063086539ee99def/66a3ddbbb4bcf37ad42f6c1b/669250d6c617e4760f3d31f1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjkyNTBkNmM2MTdlNDc2MGYzZDMxZjEiLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE3MjIwMTMxNTF9.HhnFw98y1wT1zDoEpYHHUUUN2Q_olbltjZTcJtnkDYE

########### CREATE A TODO FOR A USER BY ADMIN
POST https://todo-qa-with-ts-backend.onrender.com/api/admin/createTodo/66a3d2d6063086539ee99def/669250d6c617e4760f3d31f1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjkyNTBkNmM2MTdlNDc2MGYzZDMxZjEiLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE3MjIwMTMxNTF9.HhnFw98y1wT1zDoEpYHHUUUN2Q_olbltjZTcJtnkDYE

{
  "title":"Todo Title",
  "description":"Todo Description",
  "urgency":true,
  "deadline":"2021-06-01"
}

################# GET ALL TODO OF A USER BY ADMIN
GET https://todo-qa-with-ts-backend.onrender.com/api/admin/todo/66a3d2d6063086539ee99def/669250d6c617e4760f3d31f1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjkyNTBkNmM2MTdlNDc2MGYzZDMxZjEiLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE3MjIwMTMxNTF9.HhnFw98y1wT1zDoEpYHHUUUN2Q_olbltjZTcJtnkDYE

################ UPDATE A QA OF A USER BY ADMIN
PATCH https://todo-qa-with-ts-backend.onrender.com/api/admin/updateTodo/66a3d2d6063086539ee99def/66a4a066f3e02677ec471820/669250d6c617e4760f3d31f1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjkyNTBkNmM2MTdlNDc2MGYzZDMxZjEiLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE3MjIwMTMxNTF9.HhnFw98y1wT1zDoEpYHHUUUN2Q_olbltjZTcJtnkDYE

{
  "title":"Updated Todo Title",
  "description":"Updated Todo Description",
  "urgency":true,
  "deadline":"2021-06-01"
}

############### DELETE A TODO OF A USER BY ADMIN
DELETE https://todo-qa-with-ts-backend.onrender.com/api/admin/deleteTodo/66a3d2d6063086539ee99def/66a4a066f3e02677ec471820/669250d6c617e4760f3d31f1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjkyNTBkNmM2MTdlNDc2MGYzZDMxZjEiLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE3MjIwMTMxNTF9.HhnFw98y1wT1zDoEpYHHUUUN2Q_olbltjZTcJtnkDYE